import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Noto_Sans_Bengali({
  variable: "--font-noto_sans_bengali",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "efb-bangla-media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" data-theme="light" className={`h-full antialiased`}>
      <body
        className={`min-h-full flex flex-col max-w-7xl mx-auto ${geistSans.className}`}
      >
        <Navbar />
        <main>{children}</main>
        <Analytics />
      </body>
    </html>
  );
}
